package com.kodilla.exception.test;

public class FirstChallenge {

    /**
     * This main can throw an ArithmeticException!!!
     *
     * @param args
     */
//    public static void main(String[] args) {
//
//        FirstChallenge firstChallenge = new FirstChallenge();
//
//        try {
//            double result = firstChallenge.divide(3, 0);
//            System.out.println("wynik wynosi: " + result);
//        } catch (ArithmeticException a) {
//            System.out.println("nie można dzielić przez zero");
//        } finally {
//            System.out.println("dziekujemy za skorzystanie z programu");
//        }
//
//    }
//
//    public double divide(double a, double b) throws ArithmeticException {
//        if (b == 0) {
//            throw new ArithmeticException();
//        }
//        return a / b;
//    }
}